spring:
    application:
        name: todolist
    datasource:
        url: jdbc:mysql://localhost:3306/todo?useSSL=false
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto:update
server:
    servlet:
        context-path: /api

